client/urls.py
from django.conf.urls import url
from .views import (
    index,
    ingredient, ajax_ingredient,
    signup, login, logout, success,
    RecipeListView,
    ClientPackageListView, PackageDetailView,
    myrecipe, recipe_add, recipe_detail, recipe_edit, recipe_delete,
    ingredient_order, package_order,
    ingredient_cart, package_cart,
)

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^signup/$', signup, name="signup"),
     url(r'^login/$', login, name="login"),
     url(r'^logout/$', logout, name="logout"),
     url(r'^success/$', success, name="success"),
     url(r'^ingredient/$', ingredient, name="ingredient"),
     url(r'^ajax/ingredient/$', ajax_ingredient, name="ajax_ingredient"),
     url(r'^ingredient/order/(?P<ingredient_id>\d+)/$', ingredient_order, name='ingredient_order'),
     url(r'^recipe/$', RecipeListView.as_view(), name='recipes'),
     url(r'^package/$', ClientPackageListView.as_view(), name='packages'),
     url(r'^package/(?P<pk>\d+)/$', PackageDetailView.as_view(), name='package_detail'),
     url(r'^package/order/(?P<package_id>\d+)/$', package_order, name='package_order'),
     url(r'^cart/package/$', package_cart, name="package_cart"),
     url(r'^cart/ingredient/(?P<item_id>\d+)/$', ingredient_cart, name="ingredient_cart"),
    #  url(r'^recipe/$', recipe, name="recipe"),
     url(r'^myrecipe/$', myrecipe, name="myrecipe"),
     url(r'^myrecipe/add/$', recipe_add, name="recipe_add"),
     url(r'^myrecipe/(?P<recipe_id>\d+)/$', recipe_detail, name='recipe_detail'),
     url(r'^recipe/(?P<recipe_id>\d+)/$', recipe_detail, name='recipe_detail'),
     url(r'^myrecipe/(?P<recipe_id>\d+)/edit/$', recipe_edit, name='recipe_edit'),
     url(r'^myrecipe/(?P<recipe_id>\d+)/delete/$', recipe_delete, name='recipe_delete'),
]

client/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from partner.models import HashTag, Ingredient, Package

# Create your models here.
class  Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE )
    name = models.CharField(
            max_length=50,
            verbose_name="고객 이름",
        )

    def __str__(self):
        return self.name

class Recipe(models.Model):
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        verbose_name="ID",
    )
    title = models.CharField(
        max_length = 20,
        verbose_name="레시피명",
        )
    introduction = models.CharField(
        max_length = 100,
        verbose_name="레시피 소개",
        )
    image = models.ImageField(
        verbose_name="레시피 이미지",
    )
    hashtag = models.ManyToManyField(HashTag)
    created_date = models.DateTimeField(default=timezone.now)
    hit =  models.PositiveIntegerField()
    def __str__(self): #def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("recipe_detail", kwargs={"recipe_id":self.id})

class Recipe_stage(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
    )
    stage = models.PositiveSmallIntegerField(
        verbose_name="단계",
    )
    title = models.CharField(
        max_length = 20,
        verbose_name="단계명",
        )
    image = models.ImageField(
        verbose_name="레시피 이미지",
    )
    content = models.TextField(
        verbose_name="레시피 내용",
    )
    def __str__(self):
        return self.title

class CommentToRecipe(models.Model):
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        verbose_name="ID",
    )
    recipe = models.ForeignKey(
        Recipe,
        related_name = "recipe_comments",
        on_delete = models.CASCADE
    )
    comment = models.CharField(max_length = 200)
    score = models.PositiveSmallIntegerField(
        verbose_name="별점",
    )
    created_date = models.DateTimeField(default=timezone.now)

    # def approve(self):
    # self.approved_comment = True
    # self.save()

    def __str__(self):
        return "{} 댓글: {}".format(self.recipe.title, self.comment)


class CommentToIngredient(models.Model):
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        verbose_name="ID",
    )
    Ingredient = models.ForeignKey(
        Ingredient,
        related_name = "ingredient_comments",
        on_delete = models.CASCADE
    )
    comment = models.CharField(max_length = 200)
    score = models.PositiveSmallIntegerField(
        verbose_name="별점",
    )
    created_date = models.DateTimeField(default=timezone.now)

    # def approve(self):
    # self.approved_comment = True
    # self.save()

    def __str__(self):
        return "{} 댓글: {}".format(self.Ingredient.name, self.comment)

class IngredientItem(models.Model):
    item = models.ForeignKey(Ingredient)
    quantity = models.PositiveIntegerField(default=1)
    line_item_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __unicode__(self):
    	return self.item.title

    def remove(self):
    	return self.item.remove_from_cart()

class PackageItem(models.Model):
    item = models.ForeignKey(Package)
    quantity = models.PositiveIntegerField(default=1)
    line_item_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __unicode__(self):
    	return self.item.title

    def remove(self):
    	return self.item.remove_from_cart()

class Cart(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    ingredient_items = models.ManyToManyField(IngredientItem, blank=True)
    package_items = models.ManyToManyField(PackageItem, blank=True)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=25.00)

    def __str__(self):
        return "고객 :{}".format(self.client.username)

class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    address = models.CharField(
        max_length = 100,
        verbose_name = "주소",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    ingredients = models.ManyToManyField(
        Ingredient,
        through = 'Ordertime',
        through_fields = ('order', 'Ingredient'),
    )
    packages = models.ManyToManyField(
        Package,
        through = 'Ordertime',
        through_fields = ('order', 'Package'),
    )

    def __str__(self):
        return "고객 :{} 주소:{}".format(self.client.username, self.address)

class Ordertime(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    Ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    Package = models.ForeignKey(Package, on_delete=models.CASCADE)
    count = models.PositiveSmallIntegerField()

    def __str__(self):
        return "메뉴 :{} 수량:{}".format(self.menu.name, self.count)

partner/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Partner(models.Model):
    KOREAN = 'kr'
    CHINESE = 'ch'
    JAPANESE = 'jp'
    WESTERN ='ws'
    CATEGORY_CHOICES = (
        (KOREAN, '한식'),
        (CHINESE, '중식'),
        (JAPANESE, '일식'),
        (WESTERN, '양식'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE )
    name = models.CharField(
        max_length=50,
        verbose_name="업체 이름",
    )
    contact = models.CharField(
        max_length=50,
        verbose_name="연락처",
    )
    address = models.CharField(
        max_length=200,
        verbose_name="주소",
    )
    description = models.TextField(
        verbose_name="상세 소개",
    )
    category = models.CharField(
    max_length = 2,
    choices = CATEGORY_CHOICES,
    default = KOREAN,
    )
    def __str__(self):
        return self.name

class HashTag(models.Model):
    name = models.CharField(
        max_length = 50,
        primary_key=True
        )
    def __str__(self):
        return self.name

class Ingredient(models.Model):
    MEAT = 'mt'
    SEA_FOOD = 'sf'
    RICE = 'rc'
    KIMCHI = 'kc'
    VEGETABLE = 'vg'
    Egg = 'eg'
    PROCESS_FOOD = 'pf'
    Fruit = 'fr'
    SNACK = 'sn'
    CATEGORY_CHOICES = (
        (MEAT, '정육'),
        (SEA_FOOD, '해산물'),
        (RICE, '쌀'),
        (VEGETABLE, '채소'),
        (Egg, '알류'),
        (PROCESS_FOOD, '가공&냉장'),
        (Fruit, '과일'),
        (SNACK, '간식'),
    )
    partner =  models.ForeignKey(
        Partner,
        on_delete = models.CASCADE,
    )
    image = models.ImageField(
        verbose_name="메뉴 이미지",
    )
    name = models.CharField(
        max_length = 50,
        verbose_name="메뉴명",
        )
    price = models.PositiveIntegerField(
        verbose_name="가격",
        )
    hashtag = models.ManyToManyField(HashTag)

    category = models.CharField(
    max_length = 2,
    choices = CATEGORY_CHOICES,
    default = MEAT,
        )

    score = models.PositiveSmallIntegerField(
        verbose_name="별점",
    )
    score_string = models.CharField(
        max_length = 5,
    )
    def __str__(self):
        return self.name

class Package(models.Model):
    SIDE_DISH = 'sd'
    STEW = 'st'
    WESTERN = 'ws'
    KOREAN = 'ko'
    SIMPLE = 'sm'
    SPECIAL = 'sp'

    CATEGORY_CHOICES = (
        (SIDE_DISH, '반찬'),
        (STEW, '국/찌개'),
        (WESTERN, '양식'),
        (KOREAN, '한식'),
        (SIMPLE, '간편요리'),
        (SPECIAL, '스페셜요리'),
    )
    partner =  models.ForeignKey(
        Partner,
        on_delete = models.CASCADE,
    )

    image = models.ImageField(
        verbose_name="패키지 이미지",
    )
    name = models.CharField(
        max_length = 50,
        verbose_name="패키지명",
        )
    introduction = models.CharField(
        max_length = 100,
        verbose_name="패키지 소개",
        )
    price = models.PositiveIntegerField(
        verbose_name="가격",
        )
    hashtag = models.ManyToManyField(HashTag)

    category = models.CharField(
    max_length = 2,
    choices = CATEGORY_CHOICES,
    default = SIDE_DISH,
        )

    score = models.PositiveSmallIntegerField(
        verbose_name="별점",
    )
    score_string = models.CharField(
        max_length = 5,
    )
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("package_detail", kwargs={"pk":self.id})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=11; IE=10; IE=8; IE7; IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}sample{% endblock %}</title>
    <!-- <title /> -->
    <link rel="stylesheet" href='{% static "css/lib/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/lib/font-awesome.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/shop-homepage.css" %}'>
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
</head>
<body>
  <script type="text/javascript" src="//code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src='{% static "js/lib/jquery.multifield.js" %}'></script>
  <script src='{% static "js/lib/duplicateFields.js" %}'></script>
  <script src='{% static "js/lib/bootstrap.min.js" %}'></script>
  {% block body %}{% endblock %}
</body>
</html>

templates/edit_info.html
{% extends "base.html" %}

{% block body %}
<div class="site-wrapper" style="margin-top:30px;">
  <div class="site-wrapper-inner">
    <div class="cover-container">
    {% include "navbar.html" %}
    <div class="container">
      <div class="col-sm-6 col-sm-offset-3">
        <form method="post" action="">
          <div class="form-group">
            {% csrf_token %}
            {{partner_form.as_p}}
            <button type="submit" class="btn btn-default btn-block">저장하기</button>
          </div>
        </form>
      </div>
    </div>
    {% endblock %}
    </div>
  </div>

templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
    {% include "navbar.html" %}
      <div class="intro-header">
          <div class="container">
            {% if user.is_authenticated %}
               {% if user.partner %}
                 <div class="row">
                     <div class="col-sm-6 col-sm-offset-3">
                         <div class="intro-message">
                            <div class="header">
                              <h3 class="table-header"> {{user.username}}님 반갑습니다!</h3>
                              <a href="./edit" class="partner-setting"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                            </div>
                          <table class="patner-table table">
                           <tr>
                             <th>상호명</th>
                             <td>{{user.partner.name}}</td>
                           </tr>
                           <tr>
                             <th>전화번호</th>
                             <td>{{user.partner.contact}}</td>
                           </tr>
                           <tr>
                             <th>주소</th>
                             <td>{{user.partner.address}}</td>
                           </tr>
                           <tr>
                             <th>소개</th>
                             <td>{{user.partner.description}}</td>
                           </tr>
                         </table>
                         <hr class="intro-divider">
                         <div style="heigt: 20px;"></div>
                         <ul class="list-inline intro-social-buttons">
                             <li>
                                 <a href="./ingredient" class="btn btn-default btn-lg"><i class="fa fa-apple" aria-hidden="true"></i> <span class="network-name">&nbsp;식재료등록</span></a>
                             </li>
                             <li>
                                 <a href="./package" class="btn btn-default btn-lg"><i class="fa fa-cutlery" aria-hidden="true"></i> <span class="network-name">&nbsp;패키지등록</span></a>
                             </li>
                             <li>
                                 <a href="#" class="btn btn-default btn-lg"><i class="fa fa-check-circle" aria-hidden="true"></i> <span class="network-name">&nbsp;주문확인</span></a>
                             </li>
                         </ul>
                         </div>
                     </div>
                 </div>
              {% else %}
              <div class="row">
                 <div class="col-sm-6 col-sm-offset-3">
                      <div>
                       <h3 class="table_title">추가 정보를 입력하세요.</h3>
                     </div>
                     <form method="post" action="">
                       <div class="form-group">
                         {% csrf_token %}
                         {{partner_form.as_p}}
                         <button type="submit" class="btn btn-default btn-block">저장하기</button>
                       </div>
                     </form>
                  </div>
              </div>
              {% endif %}
            {% endif %}
          </div>
      <!-- /.container -->
      </div>
      {% endblock %}
    </div>
  </div>
</div>

templates/ingredient_list.html
{% extends "base.html" %}
{% block body %}
  {% include "navbar.html" %}
  <div class="container top30">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="header">
          <h3 class="table-header">등록된 식재료</h3>
          <a href="./ingredient" class="btn btn-default btn-sm" data-toggle="modal"
            data-target="#ingredient-add-Modal" style="padding-bottom: 5px; float: right;">
            <i class="fa fa-plus" aria-hidden="true"></i>
            <span class="network-name">&nbsp;추가</span>
          </a>
        </div>
          <table class="table">
            <tr>
              <th>이미지</th>
              <th>메뉴명</th>
              <th>가격</th>
              <th>카테고리</th>
              <!-- <th>해시태그</th> -->
              <th></th>
            </tr>
            {% for ingredient in ingredient_list %}
            <tr>
              <td><img src="{{ ingredient.image.url }}" style="max-width:100px;"></td>
              <td><a href="./{{ingredient.id}}">{{ ingredient.name }}</a></td>
              <td>{{ ingredient.price }}</td>
              <td>{{ ingredient.get_category_display }}</td>
              <td>
                <a href="./{{ingredient.id}}/edit">
                  <button style="width:60px"
                    class="btn btn-default">수정</button></a>
                <a href="./{{ingredient.id}}/delete">
                  <button style="width:60px"
                    class="btn btn-default">삭제</button></a>
              </td>
            </tr>
            {% endfor %}
          </table>
          <hr class="intro-divider">
      </div>
    </div>
    <div class="modal fade" id="ingredient-add-Modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content" style="height:400px;">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">식재료 추가</h4>
          </div>
          <div class="modal-body">
            <form enctype="multipart/form-data" method="post" action="">
                {% csrf_token %}
                <div>
                  {{ingredient_form.as_p}}
                </div>
                <input type="text" name="hashtag" class="form-control" placeholder="HashTag를 입력하세요.">
                <button type="submit" class="btn btn-default btn-block">저장하기</button>
            </form>
          </div>
          </div>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

<!--
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6">
        <a href="./add">
          <button class="btn btn-default btn-block">추가</button>
        </a>
      </div>
    </div>
-->
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}honbab{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <div class="row signup-row">
      <div class="col-md-6 col-md-offset-3">
      <form class="form-signin" method="post" action="">
        {% csrf_token %}
        <h2 class="form-signin-heading">로그인</h2>
        <input type="text"  name="username" class="form-control" placeholder="아이디" required="" autofocus="">
        <input type="password" name="password" class="form-control" placeholder="비밀번호" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> 아이디 저장
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block btn-basic" type="submit">로그인</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container-fluid contents">
  <div class="row">
     <div class="col-md-12  col-lg-12 top-image">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class=""></li>
                <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
                <li data-target="#carousel-example-generic" data-slide-to="2" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item food1">
                    <h1 class="title">금주의 레시피 TOP1</h1>
                </div>
                <div class="item food2">
                    <h1 class="title">금주의 레시피 TOP2</h1>
                </div>
                <div class="item active food3">
                    <h1 class="title">금주의 레시피 TOP3</h1>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <div class="container">
            <div class="col-md-9">
      <div class="row">
      {% for package in package_list %}
      <div class="col-sm-4 col-lg-4 col-md-4">
          <a href="./{{package.id}}">
            <div class="thumbnail">
             <img src="{{package.image.url}}" alt="">
              <div class="caption">
                  <p style="display:inline;"><a href='{{ package.get_absolute_url }}'>
                    {{package.name}}</a></p>
                    <h5>{{package.price}}원</h5>
                    <p class="pull-right" style="font-size:10px;">
                    <i class="fa fa-eye" aria-hidden="true"></i></p>
              </div>
              <div class="ratings">
                  <p>
                     {% for i in package.score_string %}
                      <i class="fa fa-star" aria-hidden="true"></i>
                     {% endfor %}
                  </p>
              </div>
          </div>
        </a>
      </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
    </div>
{% endblock %}

templates/my_recipe_list.html
{% extends "base.html" %}
{% block body %}
  {% include "navbar.html" %}
  <div class="container top30">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="header">
          <h3 class="table-header">등록된 레시피</h3>
          <a href="./add" class="btn btn-default btn-sm"
            style="padding-bottom: 5px; float: right;">
            <i class="fa fa-plus" aria-hidden="true"></i>
            <span class="network-name">&nbsp;추가</span>
          </a>
        </div>
          <table class="table">
            <tr>
              <th>이미지</th>
              <th>레시피명</th>
              <th>소개</th>
              <th></th>
              <!-- <th>해시태그</th> -->
              <th></th>
            </tr>
            {% for recipe in recipe_list %}
            <tr>
              <td><img src="{{ recipe.image.url }}" style="max-width:100px;"></td>
              <td><a href="./{{recipe.id}}">{{ recipe.title }}</a></td>
              <td>{{ recipe.introduction }}</td>
              <td></td>
              <td>
                <a href="./{{recipe.id}}/edit">
                  <button style="width:60px"
                    class="btn btn-default">수정</button></a>
                <a href="./{{recipe.id}}/delete">
                  <button style="width:60px"
                    class="btn btn-default">삭제</button></a>
              </td>
            </tr>
            {% endfor %}
          </table>
          <hr class="intro-divider">
      </div>
    </div>
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  </div>
{% endblock %}

templates/navbar.html
{% load ifusergroup_tag %}
<nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src="/static/img/logo2.png" alt=""></a>
          </div>
          <div class="navbar-collapse collapse">
            <form class="nav navbar-nav" id="nav-form">
              <div class="form-group search-box">
                <input type="text" class="form-control" placeholder="냉장고에 있는 재료를 검색하세요!">
              </div>
              <!-- <button type="hidden" class="btn btn-default">Submit</button> -->
            </form>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><i class="fa fa-bars" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i>
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                    {% if request.user|has_group:"client" %}
                      <li><a href="#">주문</a></li>
                      <li><a href="#">장바구니</a></li>
                      <li><a href="#">나의 정보</a></li>
                      <li><a href="/myrecipe/">나의 레시피</a></li>
                      <!-- <li role="separator" class="divider"></li> -->
                      <li><a href="/logout/">로그아웃</a></li>
                    {% else%}
                      <li><a href="/partner/ingredient">식재료 관리</a></li>
                      <li><a href="/partner/package">패키지 관리</a></li>
                      <li><a href="#">주문 관리</a></li>
                      <li><a href="/logout/">로그아웃</a></li>
                    {% endif %}
                  {% else %}
                      <li><a href="/login/">로그인</a></li>
                      <li><a href="/signup/">회원가입</a></li>
                  {% endif %}
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/recipe">레시피</a></li>
              <li><a href="/package">패키지</a></li>
              <li><a href="/ingredient">식재료</a></li>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>
<script>
$('.dropdown-toggle').mouseenter(function(){
  $('.dropdown-toggle').dropdown();
});
</script>

templates/order_list.html
{% extends "base.html" %}xs
{% block body %}
  {% include "navbar.html" %}
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
          <h3 class="table_title">구매하기</h3>
          <form action="" method="post">
            {% csrf_token %}
            <table class="table">
              <tr>
                <th></th>
                <th>상품명</th>
                <th>금액</th>
                <th>수량</th>
              </tr>
              <tr>
                <td><img src="{{ item.image.url }}" style="max-width:100px;"></td>
                <td>{{ item.name }}</a></td>
                <td>{{ item.price }}</td>
                <td>
                  <input class="input_number" type="number" name="{{ingredient.id}}" value="1" />
                </td>
              </tr>
            </table>
            <form action="">
              <div class="form-group">
                <label for="exampleInputEmail1">주소</label>
                <input type="email" class="form-control"  name placeholder="주소를 입력하세요.">
              </div>
            </form>
            <button type="submit" class="btn btn-default btn-block">구매</button>
          </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/package_add.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
 <div class="row">
   <div style="margin-top:30px;">
        <div class="col-md-6 col-md-offset-3">
          <h5 style="margin_bottom:20px;">패키지 추가</h5>
          <form enctype="multipart/form-data" method="post" action="">
              {% csrf_token %}
              <div>
                {{package_form.as_p}}
              </div>
              <input type="text" name="hashtag" class="form-control" placeholder="HashTag를 입력하세요.">
              <button type="submit" class="btn btn-default btn-block">저장하기</button>
          </form>
          <!-- <div id="example-1" class="content" data-mfield-options='{"section": ".group","btnAdd":"#btnAdd-1","btnRemove":".btnRemove"}'>
            <div class="row">
          		<div class="col-md-12"><button type="button" id="btnAdd-1" class="btn btn-primary">Add section</button></div>
          	</div>
            <div class="group">
              <input type="hidden" name="stage" />
              <input type="file" name="image" />
          		<div>
          			<input class="form-control" type="text" name="title">
          		</div>
          		<div>
          			<textarea class="form-control"  name="content"></textarea>
          		</div>
          		<div class="col-md-3">
          			<button type="button" class="btn btn-danger btnRemove">Remove</button>
          		</div>
          	</div>
          </div> -->
      </div>
   </div>
  </div>
</div>

<!-- <script type="text/javascript">
$('#example-1').multifield();
</script> -->
{% endblock %}

templates/package_list.html
{% extends "base.html" %}
{% block body %}
  {% include "navbar.html" %}
  <div class="container top30">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="header">
          <h3 class="table-header">등록된 패키지</h3>
          <a href="./ingredient" class="btn btn-default btn-sm" data-toggle="modal"
            data-target="#ingredient-add-Modal" style="padding-bottom: 5px; float: right;">
            <i class="fa fa-plus" aria-hidden="true"></i>
            <span class="network-name">&nbsp;추가</span>
          </a>
        </div>
          <table class="table">
            <tr>
              <th>이미지</th>
              <th>메뉴명</th>
              <th>가격</th>
              <th>카테고리</th>
              <!-- <th>해시태그</th> -->
              <th></th>
            </tr>
            {% for package in package_list %}
            <tr>
              <td><img src="{{ package.image.url }}" style="max-width:100px;"></td>
              <td><a href="./{{package.id}}">{{ package.name }}</a></td>
              <td>{{ package.price }}</td>
              <td>{{ package.get_category_display }}</td>
              <td>
                <a href="./{{ingredient.id}}/edit">
                  <button style="width:60px"
                    class="btn btn-default">수정</button></a>
                <a href="./{{ingredient.id}}/delete">
                  <button style="width:60px"
                    class="btn btn-default">삭제</button></a>
              </td>
            </tr>
            {% endfor %}
          </table>
          <hr class="intro-divider">
      </div>
    </div>
  </div>
{% endblock %}

templates/signup_success.html
{% extends "base.html" %}
{% block title %}honbab{% endblock %}
{% block body %}
{% include "navbar.html" %}
회원가입 성공!
{% endblock %}